### ISSUE TITLE
Problems with intelliJ

### ISSUE THREAD

**Issue by JojoG** [jackdreilly/SparkADMM#5]
I have some problems actually:
- first I cannot run only one objet. LestAbsDev for instance. Maj + F10 does not work. All objects are runned...
- when I do "run -> edit configurations", in the LeastAbsDev application, in the Main class section "admm.LeastAbsDev" is in red. The warning says "Main method not found in class admm.LeastAbsDev" even if it exists...
- when I use git bash, in theSparkADMM folder, the sbt command does not work.

**Comment by jackdreilly** [comment]
3) Don't use git bash for sbt. Just use cmd. we have to configure your computer to use sbt
2) no idea. we'll have to take a look together

1) are you referring running a single file? 

In the configuration, the main class refers to the name of the object residing in a package. The name of the file is ignored. Try experimenting with tdifferent numbers of objects inside files, and change their name, and change the configuration until you get a good feel of how it works.
